### ISSUE TITLE
Meta header tags are missing

### ISSUE THREAD

**Issue by loleg** [opendata-swiss/ckanext-switzerland-ng#155]
The HTML header of the page is missing descriptive `<meta>` tags, or support for OpenGraph etc. that allows rich embedding into blogs and forums. This was working in the past, and I suspect it was somewhere at [this point](https://github.com/opendata-swiss/ckanext-switzerland-ng/blob/03caa7970bda24947ae348f7f4029fd53f17ada4/ckanext/switzerland/templates/base_ogdch.html#L9) that the tags were still being injected. Please bring back the META love.

And yes, I realize that rich embedding is provided by [ckan-embed](https://github.com/opendata-swiss/ckan-embed) and that, as one might say, _"Vor der eigenen Türe wischen"_ - the component could use a refresh and more usage as well. 

Screenshot of the View Source from a random dataset, showing a bare HTML header:
![Screenshot from 2021-09-21 09-44-04](https://user-images.githubusercontent.com/31819/134133279-4b1e3577-d886-479e-9b97-5f8a14059f20.png)

**Comment by bellisk** [comment]
Hi @loleg! I'm adding a ticket to fix that. Thanks for spotting it. :)

**Comment by loleg** [comment]
Woohoo thanks @bellisk
