### ISSUE TITLE
Preview is not working

### ISSUE THREAD

**Issue by loleg** [opendata-swiss/ckanext-switzerland-ng#178]
The preview does not render inside of a dataset resource, instead an error message is shown. Seems to be a cross-site-frame-protection issue. Tested with Chrome and Firefox on this [CSV resource](https://opendata.swiss/de/dataset/covid-19-schweiz/resource/a631c80f-89ac-4032-bc23-425a07717692) being served from ckan.opendata.swiss. Opening the frame in a new window works fine. We might in any case want to add a "Open in full screen" link underneath the frame, as in for example, [dribdat projects](https://github.com/dribdat/design/raw/main/Whitepaper/images/swihack_2.png) (via [Whitepaper](https://dribdat.cc/whitepaper)).

![Screenshot from 2022-01-25 09-44-28](https://user-images.githubusercontent.com/31819/150942797-bfb485c2-92e2-49ce-8f43-db37ee2cfe47.png)

**Comment by stefina** [comment]
Thanks a lot @loleg for reporting this! This has been fixed in the meantime, sorry for only getting back to you now.

**Comment by loleg** [comment]
Looks great - thanks @stefina
